spring:
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      #uri: mongodb://[username]:[password]@[host]:[port]/[database]
      host: localhost
      port: 27017
      database: photo-manage
      username: photo-manage
      password: password

logging:
  level:
    com.nubiform: info
    org.springframework: info
    org.mongodb: info

springdoc.swagger-ui.path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

##### user-defined #####

data:
  path: /Users/nubiform/docker/volumes/photo-manage/image
  thumb-path: /Users/nubiform/docker/volumes/photo-manage/thumb-image