spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root

mybatis:
  type-aliases-package: com.nubiform.dao
  mapper-locations: classpath:/query/*.xml

data:
  path: /Users/nubiform/docker/volumes/photo-manage/image
  thumb-path: /Users/nubiform/docker/volumes/photo-manage/thumb-image