spring:
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false

  profiles:
    include:
    - datasource
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.nubiform.dao
  mapper-locations: classpath:/query/*.xml

data:
  path: /Users/nubiform/docker/volumes/photo-manage/image
  thumb-path: /Users/nubiform/docker/volumes/photo-manage/thumb-image

#logging:
#  level:
#    com.nubiform: debug
#    org.springframework: debug

springdoc.swagger-ui.path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"